import test from "node:test";
import assert from "node:assert/strict";
import {
  COMMENT_MARKER,
  findExistingRadarComment,
  upsertIssueComment,
  withCommentMarker
} from "../src/comment.js";

test("adds a stable marker to report comments", () => {
  const body = withCommentMarker("## PR Risk Radar");

  assert.ok(body.startsWith(COMMENT_MARKER));
  assert.equal(withCommentMarker(body), body);
});

test("finds marker comments before legacy generated comments", () => {
  const markerComment = { body: `${COMMENT_MARKER}\nnew`, url: "https://example.test/new" };
  const legacyComment = {
    body: "Generated by pr-risk-radar.",
    user: { type: "Bot" },
    url: "https://example.test/legacy"
  };

  assert.equal(findExistingRadarComment([legacyComment, markerComment]), markerComment);
});

test("updates an existing radar comment", async () => {
  const calls = [];
  const fetchImpl = async (url, options = {}) => {
    calls.push({ url, options });
    if (url.endsWith("?per_page=100")) {
      return Response.json([{ body: `${COMMENT_MARKER}\nold`, url: "https://api.example.test/comment/1" }]);
    }
    return Response.json({});
  };

  await upsertIssueComment({
    repo: "owner/repo",
    number: 7,
    token: "token",
    body: "## PR Risk Radar",
    fetchImpl
  });

  assert.equal(calls.length, 2);
  assert.equal(calls[1].options.method, "PATCH");
  assert.equal(calls[1].url, "https://api.example.test/comment/1");
});

test("creates a new radar comment when no existing report is found", async () => {
  const calls = [];
  const fetchImpl = async (url, options = {}) => {
    calls.push({ url, options });
    if (url.endsWith("?per_page=100")) {
      return Response.json([]);
    }
    return Response.json({});
  };

  await upsertIssueComment({
    repo: "owner/repo",
    number: 7,
    token: "token",
    body: "## PR Risk Radar",
    fetchImpl
  });

  assert.equal(calls.length, 2);
  assert.equal(calls[1].options.method, "POST");
});
