export const COMMENT_MARKER = "<!-- pr-risk-radar:report -->";

export function withCommentMarker(body) {
  return body.includes(COMMENT_MARKER) ? body : `${COMMENT_MARKER}\n${body}`;
}

export function findExistingRadarComment(comments) {
  return (
    comments.find((comment) => comment.body?.includes(COMMENT_MARKER)) ||
    comments.find(
      (comment) =>
        comment.user?.type === "Bot" &&
        comment.body?.includes("Generated by pr-risk-radar.")
    )
  );
}

async function assertOk(response, action) {
  if (!response.ok) {
    throw new Error(`Failed to ${action}: ${response.status} ${await response.text()}`);
  }
}

export async function upsertIssueComment({ repo, number, token, body, fetchImpl = fetch }) {
  if (!token || !repo || !number) {
    return;
  }

  const headers = {
    authorization: `Bearer ${token}`,
    accept: "application/vnd.github+json",
    "content-type": "application/json",
    "user-agent": "pr-risk-radar"
  };
  const markedBody = withCommentMarker(body);
  const commentsUrl = `https://api.github.com/repos/${repo}/issues/${number}/comments`;
  const commentsResponse = await fetchImpl(`${commentsUrl}?per_page=100`, { headers });
  await assertOk(commentsResponse, "list PR comments");

  const comments = await commentsResponse.json();
  const existingComment = findExistingRadarComment(comments);
  if (existingComment) {
    const updateResponse = await fetchImpl(existingComment.url, {
      method: "PATCH",
      headers,
      body: JSON.stringify({ body: markedBody })
    });
    await assertOk(updateResponse, "update PR comment");
    return;
  }

  const createResponse = await fetchImpl(commentsUrl, {
    method: "POST",
    headers,
    body: JSON.stringify({ body: markedBody })
  });
  await assertOk(createResponse, "post PR comment");
}
