function iconForRisk(risk) {
  return risk === "high" ? "HIGH" : risk === "medium" ? "MEDIUM" : "LOW";
}

export function formatMarkdown(result) {
  const lines = [
    "## PR Risk Radar",
    "",
    `**Overall risk:** ${iconForRisk(result.risk)}`,
    "",
    `Changed files: ${result.totals.changed} | Additions: ${result.totals.additions} | Deletions: ${result.totals.deletions}`,
    ""
  ];

  if (result.findings.length === 0) {
    lines.push("No obvious risk signals found. Keep the normal review flow.");
    return `${lines.join("\n")}\n`;
  }

  lines.push("### Review Focus");
  lines.push("");
  for (const finding of result.findings) {
    lines.push(`- **${finding.severity.toUpperCase()}** ${finding.label}`);
    lines.push(`  - Why it matters: ${finding.advice}`);
    lines.push(`  - Files: ${finding.files.map((file) => `\`${file}\``).join(", ")}`);
  }

  lines.push("");
  lines.push("Generated by pr-risk-radar.");
  return `${lines.join("\n")}\n`;
}

export function formatJson(result) {
  return `${JSON.stringify(result, null, 2)}\n`;
}
